version: "3.8"
services:
  backend:
    image: "uniboy/springboot-react-fullstack:24.12.2022.6.13.48"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev