version: "3.8"
services:
  backend:
    image: "uniboy/springboot-react-fullstack:31.12.2022.0.29.39"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev