version: "3.8"
services:
  backend:
    image: "uniboy/springboot-react-fullstack:6.1.2023.21.23.1"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev